//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Id_Test
    {
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public Nullable<int> count { get; set; }
    }
}
